/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uinbukittinggi.sikursus.desktop;

/**
 *
 * @author USER
 */
public class frompendaftaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frompendaftaran.class.getName());

    /**
     * Creates new form frompendaftaran
     */
   public frompendaftaran() {
    setContentPane(new BackgroundPanel());
    initComponents();

    // Panel transparan supaya gradasi terlihat
    jPanel1.setOpaque(false);

    // Warna tombol
    jButton2.setBackground(new java.awt.Color(255, 170, 220));
    jButton3.setBackground(new java.awt.Color(255, 170, 220));
    jButton4.setBackground(new java.awt.Color(255, 170, 220));
    jButton5.setBackground(new java.awt.Color(255, 170, 220));

    // Tombol Proses
    jButton6.setBackground(new java.awt.Color(80, 200, 200));
    jButton6.setForeground(java.awt.Color.WHITE);

    // Tombol Reset
    jButton7.setBackground(new java.awt.Color(240, 120, 190));
    jButton7.setForeground(java.awt.Color.WHITE);

    // Input
    jTextField1.setBackground(java.awt.Color.WHITE);
    jTextField2.setBackground(java.awt.Color.WHITE);
    jTextField3.setBackground(java.awt.Color.WHITE);
    jTextField4.setBackground(java.awt.Color.WHITE);

    // Hasil
    jTextArea1.setBackground(java.awt.Color.WHITE);

    setTitle("Form Pendaftaran Kursus");
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Nama");

        jButton3.setText("Biaya");

        jButton4.setText("Jumlah");

        jButton5.setText("Kursus");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton6.setText("Proses");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Reset");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton6)
                        .addGap(197, 197, 197)
                        .addComponent(jButton7)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String nama = jTextField1.getText();
    String biaya = jTextField2.getText();
    String jumlah = jTextField3.getText();
    String kursus = jTextField4.getText();

    jTextArea1.setText(
        "Nama   : " + nama +
        "\nBiaya  : Rp" + biaya +
        "\nJumlah : " + jumlah +
        "\nKursus : " + kursus
    );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextArea1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frompendaftaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
private class BackgroundPanel extends javax.swing.JPanel {

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);

        java.awt.Graphics2D g2 =
                (java.awt.Graphics2D) g.create();

        int lebar = getWidth();
        int tinggi = getHeight();

        // GRADASI PINK -> BIRU
        java.awt.GradientPaint gradasi =
                new java.awt.GradientPaint(
                        0, 0,
                        new java.awt.Color(255, 190, 225),
                        lebar, tinggi,
                        new java.awt.Color(170, 215, 255)
                );

        g2.setPaint(gradasi);
        g2.fillRect(0, 0, lebar, tinggi);

        // 🦋 KUPU-KUPU
        gambarKupu(g2, lebar - 60, 70, 1.0);
        gambarKupu(g2, lebar - 60, 150, 0.8);
        gambarKupu(g2, lebar - 60, 230, 1.0);
        gambarKupu(g2, lebar - 60, 310, 0.8);

        g2.dispose();
    }

    private void gambarKupu(
            java.awt.Graphics2D g2,
            int x,
            int y,
            double ukuran) {

        int a = (int)(25 * ukuran);
        int b = (int)(30 * ukuran);

        // Sayap kiri
        g2.setColor(new java.awt.Color(255, 100, 180));
        g2.fillOval(x - a, y - b / 2, a, b);

        // Sayap kanan
        g2.setColor(new java.awt.Color(100, 160, 255));
        g2.fillOval(x, y - b / 2, a, b);

        // Sayap bawah kiri
        g2.setColor(new java.awt.Color(255, 170, 220));
        g2.fillOval(x - a + 5, y + 3, a - 8, b - 10);

        // Sayap bawah kanan
        g2.setColor(new java.awt.Color(160, 200, 255));
        g2.fillOval(x + 3, y + 3, a - 8, b - 10);

        // Badan
        g2.setColor(new java.awt.Color(80, 60, 110));
        g2.fillOval(x - 3, y - 8, 6, 23);

        // Kepala
        g2.fillOval(x - 4, y - 14, 8, 8);

        // Antena
        g2.setStroke(new java.awt.BasicStroke(1.5f));
        g2.drawArc(x - 13, y - 22, 13, 13, 20, 100);
        g2.drawArc(x, y - 22, 13, 13, 60, 100);
    }
}
}
